baseURL: https://grkamalov.netlify.app/
languageCode: en-us
title: Portfolio website, Georgy Kamalov, MFA'22, LBS
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    subtitle: |-
      A RESPONSIVE SITE TEMPLATE DESIGNED BY HTML5 UP
      AND RELEASED UNDER THE CREATIVE COMMONS.
    title: Hi! My name is Georgy, I am an aspiring finance professional coming from Moscow. 
  blog: {}
  contact:
    address:
      - city: London
        country: United Kingdom
        street: 28B Randolph Crescent, W9 1DR
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: georgy.kamalov@gmail.com
        title: Email
    enable: yes
    phone:
      - phone: (+44) 7763-775161 
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Georgy Kamalov
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
      #- icon: fa-twitter
      #  label: Twitter
      #  url: https://www.twitter.com
      #- #icon: fa-facebook
       # label: Facebook
      #  url: https://www.facebook.com
      #- #icon: fa-instagram
      #  label: Instagram
       # url: https://www.instagram.com
      - icon: fa-github
        label: GitHub
        url: https://github.com/GRKamalov
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/grkamalov
  image: ''
  name: Your name
  navigation:
    button1:
      - name: Get Started
        url: blogs
    button2:
      - name: Log In
        url: '#'
    links:
      - name: Home
        url: '#'
      - name: Blogs
        url: blogs
      - name: Generic Blog
        url: blogs/ipsum
      - name: Elements
        url: elements.html
    menu: Menu
    subtitle: By HTML5 Up
    title: Forty
  tiles:
    enable: yes
    showcase:
      - image: pic01.jpg
        subtitle: 
        title: Autobiography
        url: blogs/biography
      - image: pic02.jpg
        subtitle: 
        title: Data Science 
        url: blogs/ds
      - image: pic03.jpg
        subtitle: Data Analytics for Finance
        title: London Business School 
        url: blogs/lbs
      - image: pic04.jpg
        subtitle: Science fiction; history - to be added
        title: Reading list
        url: blogs/books
      - image: pic05.jpg
        subtitle: 
        title: Curriculim Vitae
        url: blogs/cv
  
  
  two:
    buttonText: Browse
    enable: yes
    subtitle: 
    title: Thank you very much for visiting this webpage!
    url: blogs

